version: "3.1"

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --init-file /docker-entrypoint.initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: asiago
    volumes:
      - ./sqls:/docker-entrypoint.initdb.d
    networks:
      - shared_network
    ports:
      - "3306:3306"
networks:
  shared_network: