version: "3.1"

services:
  nicely_app:
    container_name: nicely_app
    environment: 
      - GOOGLE_CLOUD_NATURAL_LANGUAGE_API_URL=https://language.googleapis.com/v1/documents:analyzeSentiment
      - COMMIT_HASH=cd7daa643ffa505ae3b465beaa583df42246f4f2
      - DATABASE_HOSTNAME=0.0.0.0
      - DATABASE_USERNAME=nicely
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=asiago
      - NODE_ENV=development
      - JWT_SECRET=superSecret
    volumes:
      - ./:/src
    build:
        context: .
    command: npm test
    networks:
      - shared_network
    ports:
      - "3000:3000"
networks:
  shared_network: