on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*.*"
  pull_request:

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: asiago
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Setup Python version"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "[STEP] Build Docker image"
        run: |
          docker build . -t nicely_app:${{github.sha}}
