on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*.*"
  pull_request:

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306

        env:
          MYSQL_USER: nicely
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: asiago
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Setup pipeline environment variables"
        run: |
          echo "::set-output name=MY_GIT_SHA::$(git rev-parse --short "$GITHUB_SHA")"
          echo "::set-output name=MY_IMAGE_TAG::${GITHUB_REF#refs/*/}"

      - name: "[STEP] Set Node.js version"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "[STEP] Install app dependencies"
        run: npm install

      - name: "[STEP] Run Integration Tests"
        run: docker-compose -f ./docker-compose-ci.yml run nicely_app